### ISSUE TITLE
SCMB client reconnet issue

### ISSUE THREAD

**Issue by maksmyung** [HewlettPackard/oneview-sdk-java#8]
This issue is tested using ScmbClient in Samples project and has an affect on two versions of sdk - 1.2 and 2.0.
The SCMB client starts again incorrectly after invocation of `scmbClient.stopScmb()`:
`scmbClient.scmbProcessor();`
`<some timeout to receive messages>`
`scmbClient.stopScmb();`
`scmbClient.scmbProcessor();`
There is an AlreadyClosedExcepption on the second invocation of `scmbClient.scmbProcessor();`:
`Exception in thread "pool-4-thread-2" com.rabbitmq.client.AlreadyClosedException: connection is already closed due to clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
    at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:195)
    at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:228)
    at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:214)
    at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118)
    at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:833)
    at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.queueDeclare(AutorecoveringChannel.java:259)
    at com.hp.ov.sdk.messaging.scmb.services.ScmbProcessor.run(ScmbProcessor.java:57)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)`

**Comment by maksmyung** [comment]
I think this method `ScmbProcessor.releaseScmbThread()` works incorrectly cause this one exception occurs when the method above is runnig:
`java.io.IOException
    at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106)
    at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102)
    at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:124)
    at com.rabbitmq.client.impl.ChannelN.basicGet(ChannelN.java:985)
    at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicGet(AutorecoveringChannel.java:335)
    at com.hp.ov.sdk.messaging.scmb.services.ScmbProcessor.run(ScmbProcessor.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)`
`Caused by: com.rabbitmq.client.ShutdownSignalException: clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
    at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67)
    at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33)
    at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:348)
    at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:221)
    at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118)
    ... 6 more`

**Comment by maksmyung** [comment]
The problem is that the tasks in the executor service are not terminated correctly on `ScmbConnectionManager.stopScmb(RestParams)` and keep runnig. So I've fixed that by adding this code to `stopScmb()`:

`scmbProcessThreadQueue.remove(key);`
`ExecutorService executor = getExecutor(params.getHostname());`
`executor.shutdownNow();`
 `try {`
`executor.awaitTermination(5, TimeUnit.SECONDS);`
`} catch (InterruptedException e) {`
`LOGGER.warn("Termination of executor's tasks is interrupted", e);`
`}`
`removeExecutor(params.getHostname());`
And I've removed `this.interrupt()` invocation from `ScmbProcessor.releaseScmbThread()`.

**Comment by lhsvobodaj** [comment]
@maksmyung 

Is it possible for you to update the SDK version? We have just released a new version of the SDK (3.0.0) with lots of improvements. If it is possible, I recommend you to update the SDK to the latest version and start using the new state-changed message bus client.

**Comment by maksmyung** [comment]
@lhsvobodaj 
Thank you!
I'm just going to update the SDK by the new one

**Comment by lhsvobodaj** [comment]
Great! Feel free to contact us in case you find any issues while using the SDK.

About the SCMB, it would be great if you could share with us your experience using the version 3.0.0 of the SDK.

**Comment by CintiaLopes** [comment]
Closing since the issue should be fixed.
